name: Trigger Deploy Script on Private Server

on:
  workflow_dispatch:  # Manual trigger

jobs:
  deploy:
    # Specify the exact name of the self-hosted runner
    runs-on: [self-hosted, ankush-runner]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up SSH Key
        run: |
          echo "${{ secrets.PRIVATE_SERVER_KEY }}" > private-server.pem
          chmod 600 private-server.pem

      - name: Trigger Deploy Script on Private Server
        run: |
          ssh -o StrictHostKeyChecking=no -i private-server.pem ${{ secrets.PRIVATE_SERVER_USER }}@${{ secrets.PRIVATE_SERVER_IP }} "bash /home/ubuntu/deploy.sh"

      - name: Clean Up
        run: rm -f private-server.pem
